name: build
on: 
  push: 
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # 这是github官方的一个action，用于clone该仓库的源码到工作流中，
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          cd my-project # 进入项目目录
          npm install  # 安装依赖
          npm run build  # 执行打包
  
      # 连接到ssh，并且做一个拷贝操作的action
      - name: Deploy 🚀
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
         host: ${{ secrets.SERVER_HOST }}
         user: ${{ secrets.SERVER_USER }}
         pass: ${{ secrets.SERVER_PASS }}
         connect_timeout: 10s
         local: './dist/*' # 这里是下一步要创建的vue项目构建完成后的静态资源路径
         remote: /usr/local/caddy/site2 # 这里是 step1 中，在服务器上创建用于存放静态资源的文件夹

